spring:
  application:
    name: basket-service

    data:
      mongodb:
        host: localhost
        port: 27012
        database: basket-service
      redis:
        host: localhost
        port: 6379
        password: sa

      cache:
        redis:
          time-to-list: 6000

basket:
  client:
    platzi: https://api.escuelajs.co/api/v1